# ====================== 网站全局设置 ======================
title                    : "Yang Gu"       #【改这里】网页标题，你的英文名字，浏览器标签栏显示
description              : "Fourth-year undergraduate student in Communication Engineering at Nanjing University of Posts and Telecommunications (NJUPT), focusing on Direction-of-Arrival estimation."
#【改这里】一句话简介，简单描述你的研究方向，用于搜索引擎展示，例："PhD student at Shanghai Jiao Tong University, focusing on AI‑empowered wireless communications."
repository               : "gu275/gu275.github.io"
#【必须修改】改成你自己仓库，格式："gu275/gu275.github.io"
google_scholar_stats_use_cdn : true   # 保持true，开启谷歌学者引用统计CDN加速，不用改
# google analytics
google_analytics_id      :  #【可选】谷歌分析ID，没有就留空，不需要删除
# SEO Related 搜索引擎收录，全部没有就留空
google_site_verification :  #【可选】google搜索控制台验证ID
bing_site_verification   :  #【可选】必应站长平台验证ID
baidu_site_verification  :  #【可选】百度站长平台验证ID
# ====================== 作者个人信息（重点修改区域） ======================
author:
  name             : "Yang Gu"     #【改这里】你的姓名，例如 "Yang Gu"
  avatar           : "images/android-chrome-512x512.png"
  #【改这里】头像文件路径，把你的照片上传images文件夹，填写文件名，例："images/my_photo.jpg"
  bio              : "Incoming Phd @ Shanghai Jiao Tong University (SJTU)"
  #【改这里】身份简介，例："PhD Candidate, Shanghai Jiao Tong University"
  location         : "Nanjing, China"  #【改这里】所在地，例："Shanghai, China"
  employer         :  #【可选】工作单位，一般bio写了这里可以空着
  pubmed           :  #【可选】医学pubmed链接，通信方向留空
  googlescholar    : "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"
  #【改这里】完整谷歌学术主页链接，复制浏览器地址栏URL粘贴过来
  email            : "b23010526@njupt.edu.cn" #【改这里】你的邮箱，会显示在主页
  researchgate     :  #【可选】ResearchGate完整主页链接，不用就空
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Gu275" #【改这里】你的github用户名，不是完整链接！例如 "gu275"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #【可选】impactstory个人主页链接
  lastfm           :
  linkedin         : #【可选】linkedin用户名，不是完整url
  dblp             : #【可选】DBLP完整个人主页链接
  orcid            : "https://orcid.org/0009-0003-5769-1877" #【可选】ORCID号完整链接
  pinterest        :
  soundcloud       :
  stackoverflow    : #【可选】stackoverflow个人主页链接
  steam            :
  tumblr           :
  twitter          :  #【可选】X(Twitter)用户名
  vine             :
  weibo            : #【可选】微博用户名
  xing             :
  youtube          :
  wikipedia        :
